// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nufmjpnvpqewqlyxlhic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51Zm1qcG52cHFld3FseXhsaGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MDIzMzcsImV4cCI6MjA1Nzk3ODMzN30._NWo7hJiqgG4TFiu3fk7Ha-rJAb7yz3jY1jE0bZ1V9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);